core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('service/', ServicesView.as_view(), name='service'),
    path('recources/', ResourcesView.as_view(), name='recources'),
    path('finder/', FinderView.as_view(), name='finder'),
    path('contact/', ContactView.as_view(), name='contact'),
]

sageserv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.utils import timezone
from django.contrib import messages
from django.views.generic import TemplateView

# Create your views here.

class HomeView(TemplateView):
    template_name = "index.html"

class AboutView(TemplateView):
    template_name = "about.html"


class ServicesView(TemplateView):
    template_name = "services.html"


class ResourcesView(TemplateView):
    template_name = "resources.html"


class FinderView(TemplateView):
    template_name = "finder.html"


class ContactView(TemplateView):
    template_name = "contact.html"

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

      <section class="section section-intro context-dark">
        <div class="intro-bg" style="background: url(static/images/intro-bg-1.jpg) no-repeat;background-size:cover;background-position: top center;"></div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-8 text-center">
              <h1 class="font-weight-bold wow fadeInLeft">About Us</h1>
              <p class="intro-description wow fadeInRight">Feel free to learn more about our team and company on this page. We are always happy to help you!</p>
            </div>
          </div>
        </div>
      </section>
      <!-- About page about section-->
      <section class="section section-md">
        <div class="container">
          <div class="row row-40 justify-content-center">
            <div class="col-lg-6 col-12">
              <div class="offset-top-45 offset-lg-right-45">
                <div class="section-name wow fadeInRight" data-wow-delay=".2s">About us</div>
                <h3 class="wow fadeInLeft text-capitalize" data-wow-delay=".3s">A Few Words<span class="text-primary"> about us</span></h3>
                <p class="font-weight-bold text-gray-dark wow fadeInUp" data-wow-delay=".4s">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum nulla ac tincidunt malesuada. Sed volutpat semper elit quis pharetra. Etiam sodales a sem vitae fermentum.</p>
                <p class="wow fadeInUp" data-wow-delay=".4s">Sapien eget mi proin sed libero enim sed faucibus turpis. Placerat in egestas erat imperdiet sed euismod nisi. Vulputate eu scelerisque felis imperdiet. Lorem donec massa sapien faucibus. Volutpat diam.</p>
                <p class="wow fadeInUp" data-wow-delay=".4s">Adipiscing enim eu turpis egestas pretium aenean pharetra magna. Nullam non nisi est sit amet facilisis magna etiam. Nec feugiat in fermentum posuere urna nec.</p>
                <div class="offset-top-20">
                 
                </div>
              </div>
            </div>
            <div class="col-lg-6 col-sm-10 col-12">
              <div class="block-decorate-img wow fadeInLeft" data-wow-delay=".2s"><img src="{% static 'images/about-1-570x703.jpg' %}" alt="" width="570" height="351"/>
              </div>
            </div>
          </div>
        </div>
      </section>
     
      {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
  <head>
    <title>Sage SERV</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Montserrat:300,400,700%7CPoppins:300,400,500,700,900">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>.ie-panel{display: none;background: #212121;padding: 10px 0;box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);clear: both;text-align:center;position: relative;z-index: 1;} html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {display: block;}</style>
  </head>
  <body>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="{% static 'images/ie8-panel/warning_bar_0000_us.jpg' %}" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <div class="preloader">
      <div class="preloader-body">
        <div class="cssload-container">
          <div class="cssload-speeding-wheel"></div>
        </div>
        <p>Loading...</p>
      </div>
    </div>
      {% include "snippets/navbar.html" %}

      {% block content %}
      
      {% endblock content %}

      {% include "snippets/footerbar.html" %}
    <script src="{% static 'js/core.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <!--coded by Drel-->
  </body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
      <section class="section section-intro context-dark">
        <div class="intro-bg" style="background: url(static/images/intro-bg-1.jpg) no-repeat;background-size:cover;background-position: top center;"></div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-8 text-center">
              <h1 class="font-weight-bold wow fadeInLeft">Contacts</h1>
              <p class="intro-description wow fadeInRight">Ut enim ad minim laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>
          </div>
        </div>
      </section>
      <!--Mailform-->
      <section class="section section-md">
        <div class="container">
          <!--RD Mailform-->
          <div class="row justify-content-center">
            <div class="col-xl-6 col-md-8 col-12">
              <form class="rd-mailform text-left" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php">
                <div class="form-wrap">
                  <label class="form-label" for="contact-name">Name<span class="req-symbol">*</span></label>
                  <input class="form-input" id="contact-name" type="text" name="name" data-constraints="@Required">
                </div>
                <div class="form-wrap">
                  <label class="form-label" for="contact-phone">Phone<span class="req-symbol">*</span></label>
                  <input class="form-input" id="contact-phone" type="text" name="phone" data-constraints="@Required @PhoneNumber">
                </div>
                <div class="form-wrap">
                  <label class="form-label" for="contact-email">E-Mail<span class="req-symbol">*</span></label>
                  <input class="form-input" id="contact-email" type="email" name="email" data-constraints="@Required @Email">
                </div>
                <div class="form-wrap">
                  <label class="form-label label-textarea" for="contact-message">Message<span class="req-symbol">*</span></label>
                  <textarea class="form-input" id="contact-message" name="message" data-constraints="@Required"></textarea>
                </div>
                <!--Google captcha-->
                <div class="form-wrap text-left form-validation-left">
                  <div class="recaptcha" id="captcha1" data-sitekey="6LfZlSETAAAAAC5VW4R4tQP8Am_to4bM3dddxkEt"></div>
                </div>
                <div class="form-button group-sm text-center text-lg-left">
                  <button class="button button-primary" type="submit">Send</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>
      <!--Google Map-->
      <section class="section">
        <!--Please, add the data attribute data-key="YOUR_API_KEY" in order to insert your own API key for the Google map.-->
        <!--Please note that YOUR_API_KEY should replaced with your key.-->
        <!--Example: <div class="google-map-container" data-key="YOUR_API_KEY">-->
        <div class="google-map-container contacts-map" data-center="9870 St Vincent Place, Glasgow, DC 45 Fr 45." data-zoom="5" data-icon="images/gmap_marker.png" data-icon-active="images/gmap_marker_active.png" data-styles="[{&quot;featureType&quot;:&quot;landscape&quot;,&quot;stylers&quot;:[{&quot;saturation&quot;:-100},{&quot;lightness&quot;:60}]},{&quot;featureType&quot;:&quot;road.local&quot;,&quot;stylers&quot;:[{&quot;saturation&quot;:-100},{&quot;lightness&quot;:40},{&quot;visibility&quot;:&quot;on&quot;}]},{&quot;featureType&quot;:&quot;transit&quot;,&quot;stylers&quot;:[{&quot;saturation&quot;:-100},{&quot;visibility&quot;:&quot;simplified&quot;}]},{&quot;featureType&quot;:&quot;administrative.province&quot;,&quot;stylers&quot;:[{&quot;visibility&quot;:&quot;off&quot;}]},{&quot;featureType&quot;:&quot;water&quot;,&quot;stylers&quot;:[{&quot;visibility&quot;:&quot;on&quot;},{&quot;lightness&quot;:30}]},{&quot;featureType&quot;:&quot;road.highway&quot;,&quot;elementType&quot;:&quot;geometry.fill&quot;,&quot;stylers&quot;:[{&quot;color&quot;:&quot;#ef8c25&quot;},{&quot;lightness&quot;:40}]},{&quot;featureType&quot;:&quot;road.highway&quot;,&quot;elementType&quot;:&quot;geometry.stroke&quot;,&quot;stylers&quot;:[{&quot;visibility&quot;:&quot;off&quot;}]},{&quot;featureType&quot;:&quot;poi.park&quot;,&quot;elementType&quot;:&quot;geometry.fill&quot;,&quot;stylers&quot;:[{&quot;color&quot;:&quot;#b6c54c&quot;},{&quot;lightness&quot;:40},{&quot;saturation&quot;:-40}]},{}]">
          <div class="google-map"></div>
          <ul class="google-map-markers">
            <li data-location="9870 St Vincent Place, Glasgow, DC 45 Fr 45." data-description="9870 St Vincent Place, Glasgow"></li>
          </ul>
        </div>
      {% endblock content %}

templates/finder.html
{% extends "base.html" %}
{% load static %}
{% block content %}

      <section class="section section-intro context-dark">
        <div class="intro-bg" style="background: url(images/intro-bg-2.jpg) no-repeat;background-size:cover;background-position: top center;"></div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-8 text-center">
              <h1 class="font-weight-bold wow fadeInLeft">FIND MY PHONE</h1>
              <p class="intro-description wow fadeInRight">Find my phone</p>
            </div>
          </div>
        </div>
      </section>
      <!--Base typography -->
      <section class="section section-lg bg-default">
        <div class="container">
          <div class="row row-50 flex-lg-row-reverse">
            <div class="col-xl-4">
              <ul class="list-md">
               
              </ul>
            </div>
            <div class="col-xl-8">
              <ul class="list-xl">
                  <h3>Device Identity</h3>
                  <p>Just input the IMEI and get information about any device, see all device specifications, stolen report status, network lock status, sim-lock check, and Mobile IP Blacklist Check.</p>
                  <p>The GSMA maintains a unique system known as the International Mobile Equipment Identity Database, use it to check for device specifications and other details about any mobile phone.</p>
                </li>
                <li> <div class="form-button group-sm text-center text-lg-left">
                    <a href="https://osintframework.com/"> <button class="button button-primary" type="submit">Try Now</button></a>
                  </div></li>
                <li>
                  <h3>Use find my phone Android and iPhone</h3>
                  <p>Find my iPhone: https://www.icloud.com/find</p>
                  <p>Find, lock, or erase a lost Android device</p>
                  <p>If you lose an Android phone or tablet or Wear an OS watch, you can find, lock, or erase it. If you've added a Google Account to your device, Find My Device is automatically turned on. <a href="https://support.google.com/android/answer/3265955"> Learn how to make sure that your device can be found if it gets lost.</a>

                    To find, lock, or erase an Android phone, that phone must:</p>
                  
                         <ul class="list-marked">
                            <li>Be turned on</li>
                            <li>Be signed in to a Google Account</li>
                            <li>Be connected to mobile data or Wi-Fi</li>
                            <li>Be visible on Google Play</li>
                            <li>Have Location turned on</li>
                            <li>Have Find My Device turned on</li>
                          </ul>
                          <p>If you used your lost phone for 2-step verification, you must have a <a href="https://support.google.com/accounts/answer/1188780">  backup phone</a> or <a href="https://support.google.com/accounts/answer/1187538"> backup code.</a></p>
                        
              
                  <p>Remotely find, lock, or erase</p>
                  <ol class="list-ordered">
                    <li>Go to
                        <a href="https://support.google.com/nexus/answer/2865483">  android.com/find </a> and sign in to your Google Account.
                       <ul class="list-marked">
                        <li>If you have more than one phone, click the lost phone at the top of the screen.</li>
                        <li>If your lost phone has more than one user profile, sign in with a Google Account that's on the main profile.<a href="https://support.google.com/nexus/answer/2865483">  Learn about user profiles.</a></li>
                      </ul></li>
                    <li>The lost phone gets a notification.</li>
                    <li>On the map, you'll get info about where the phone is.
                        <ul class="list-marked">
                            <li>The location is approximate and might not be accurate.</li>
                            <li>IIf your phone can't be found, you'll see its last known location, if available.</li>
                          </ul></li>
                          <li>Pick what you want to do. If needed, first click Enable lock & erase. 
                          <ul class="list-marked">
                            <li>Play sound: Rings your phone at full volume for 5 minutes, even if it's set to silent or vibrate.</li>
                            <li>Secure device: Locks your phone with your PIN, pattern, or password. If you don't have a lock, you can set one. To help someone return your phone, you can add a message or phone number to the lock screen.</li>
                            <a>Erase device: Permanently deletes all data on your phone (but might not delete SD cards). After you erase it, Find My Device won't work on the phone.
                                Important: If you find your phone after erasing, you'll likely need your Google Account password to use it again. <a href="https://support.google.com/android/answer/9459346?visit_id=638035498177369454-3197538617&rd=1"> Learn about device protection. </a>  </li>
                          </ul></li>
                        </ol>
                        <br>
                          <h4>Find with an app</h4>
                          <ol class="list-ordered">
                        <li>On another Android phone or tablet, open the Find My Device app.
                                If the other device doesn't yet have the app, <a href="https://accounts.google.com/ServiceLogin/signinchooser?passive=1209600&osid=1&continue=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.adm&followup=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.adm&authuser=0&ifkv=ARgdvAu64Uo7pTo1AIFzsZT6dy1lZFSy_3pXTjzsS2oSDOXTspQdZgsbGHTe0q1m5FiCUzASUWbARg&flowName=GlifWebSignIn&flowEntry=ServiceLogin"> get it on Google Play.</a></li>
                          <li>Sign in.
                            <ul class="list-marked">
                                <li>If your own device is lost, tap Continue as [your name].</li>
                                <li>If you're helping a friend, tap Sign in as a guest and let your friend sign in.</li>
                                <li>IFollow the same steps as listed above. <a href="https://support.google.com/accounts/answer/6160491?hl=en#web"> Continue to steps.</a></li>
                                <li>Find with your Wear OS watch</li>
                                <p>If you lose your phone or tablet that’s connected to a Wear OS smartwatch, you may be able to find it with your watch. Learn how to find your phone with your watch.</p>
                              <br>
                               <h4>How Find My Device handles your data</h4>  
                              <p>Google collects certain information to help you find a lost Android device. Some of this functionality uses Google Play services. For example, Find My Device collects:</p>
                              <ul class="list-marked">
                                <li>Approximate and precise locations and device or other identifiers for service functionality purposes.</li>
                                <li>Personal identifiers for service functionality, fraud prevention, security, and compliance purposes. We use these identifiers to associate your Android devices to your account.</li>
                              </ul>
                              <p>The data that Find My Device collects is encrypted in transit. You can delete all devices and their locations through the Find My Device app.</p>
                            </ul></li>
                          </ol>   
                  </ol>
              </ul>
            </div>
          </div>
        </div>
      </section>
 
    
        {% endblock content %}

templates/resources.html
{% extends "base.html" %}
{% load static %}
{% block content %}

      <section class="section section-intro context-dark">
        <div class="intro-bg" style="background: url(images/intro-bg-2.jpg) no-repeat;background-size:cover;background-position: top center;"></div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-xl-8 text-center">
              <h1 class="font-weight-bold wow fadeInLeft">Resources</h1>
              <p class="intro-description wow fadeInRight">Lots of Customization Options</p>
            </div>
          </div>
        </div>
      </section>
      <!--Base typography -->
      <section class="section section-lg bg-default">
        <div class="container">
          <div class="row row-50 flex-lg-row-reverse">
            <div class="col-xl-4">
                <ul class="list-md">
                    <li>
                      <h3>OISNT TOOLS</h3>  
                      <p>There are just too many records and data to go through. Thankfully, many tools have been created to automate and speed up the process</p>
                
                    </li>
                    <li> <div class="form-button group-sm text-center text-lg-left">
                        <a href="https://osintframework.com/"> <button class="button button-primary" type="submit">Try Now</button></a>
                      </div></li>
                      <li>   <br></li>
                      <li>
                        <h3>SAGE-ARMADA</h3>  
                        <p>Have you or a client ever lost bitcoin as a result of a phishing, ransomware, fraudulent ICO, or fraudulent investment? Have you been compromised? We'll assist.</p>
                  
                      </li>
                      <li> <div class="form-button group-sm text-center text-lg-left">
                          <a href="https://osintframework.com/"> <button class="button button-primary" type="submit">Get Statred</button></a>
                        </div></li>
                    
                  </ul>
            </div>
            <div class="col-xl-8">
              <ul class="list-xl">
                <li>
                  <h1>Sage Serv can Help</h1>
                  <p>Senior forensic financial investigators at Sageserv have a wealth of knowledge performing comprehensive, challenging investigations. Our in-house developed program finds connections between cryptocurrency addresses, bank accounts, and other entities like criminals, dark marketplaces, mixers, and on- and off-ramps.</p>
                  <p>Our hired services can produce evidence that can be used as actionable intelligence in legal proceedings including money laundering, drug trafficking, financing of terrorism, ransomware, and other crimes. Our team delivers written, in-depth reports on the investigations it has carried out, which have been used and supported in court. When it's time to prosecute and collect assets, our expert witness services might be helpful in court.</p>
                  <p>Additionally, Sageserv provides free investigations through the Defenders League, a team of volunteers from colleges and universities all around the world who have been trained to find money stolen or lost in cryptocurrency fraud. Law enforcement is forced to concentrate on major, high-profile cases as a result of the upward trend of rising crypto theft, scams, and fraud, while victims of "minor" losses are frequently left to fend for themselves.</p>
                  <p> However, these “smaller” losses can add up to big numbers, damaging trust in the industry. This is why the Sageserv Defenders League’s services are available pro bono, as it marks a significant step forward toward Sageserv's primary goal of making the internet a safe, trusted, and broadly adopted asset class.</p>
                </li>
               
              </ul>
            </div>
          </div>
        </div>
      </section>
     
        {% endblock content %}

templates/snippets/footerbar.html
{% load static %}
      <!--Footer-->
      <footer class="section footer-classic section-sm">
        <div class="container">
          <div class="row row-30">
            <div class="col-lg-3 wow fadeInLeft">
              <!--Brand--><a class="brand" href="{% url 'core:home' %}"><img class="brand-logo-dark" src="{% static 'images/logo-default-200x34.png' %}" alt="" width="100" height="17"/><img class="brand-logo-light" src="{% static 'images/logo-default-200x34.png' %}" alt="" width="100" height="17"/></a>
              <p class="footer-classic-description offset-top-0 offset-right-25">To provide justice to those who need it, solve the crime and do impossible actions within the bounds of the law.</p>
            </div>
            <div class="col-lg-3 col-sm-8 wow fadeInUp">
              <P class="footer-classic-title">contact info</P>
              <div class="d-block offset-top-0">Sage Security Services, No 22 Kano street, FCT - Abuja, Nigeria</span></div><a class="d-inline-block accent-link" href="mailto:#">inquiry@sageserv.tech</a><a class="d-inline-block" href="tel:#">+234-913-895-5830</a>
              <ul>
                <li>Mon-Thu:<span class="d-inline-block offset-left-10 text-white">8:00 AM - 8:00 PM</span></li>
                <li>Fri:<span class="d-inline-block offset-left-10 text-white">10:00 AM - 8:00 PM</span></li>
              </ul>
            </div>
            <div class="col-lg-2 col-sm-4 wow fadeInUp" data-wow-delay=".3s">
              <P class="footer-classic-title">Quick Links</P>
              <ul class="footer-classic-nav-list">
                <li><a href="{% url 'core:home' %}">Home</a></li>
                <li><a href="{% url 'core:about' %}">About us</a></li>
                <li><a href="{% url 'core:service' %}">Services</a></li>
                <li><a href="{% url 'core:contact' %}">Contacts</a></li>
              </ul>
            </div>
            <div class="col-lg-4 wow fadeInLeft" data-wow-delay=".2s">
              <P class="footer-classic-title">newsletter</P>
              <form class="rd-mailform text-left footer-classic-subscribe-form" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php">
                <div class="form-wrap">
                  <label class="form-label" for="subscribe-email">Your Email Address</label>
                  <input class="form-input" id="subscribe-email" type="email" name="email" data-constraints="@Email @Required">
                </div>
                <div class="form-button group-sm text-center text-lg-left">
                  <button class="button button-primary button-circle" type="submit">sign up</button>
                </div>
              </form>
              <p>Be the first to find out about our latest news, updates, and special offers.</p>
            </div>
          </div>
        </div>
        <div class="container wow fadeInUp" data-wow-delay=".4s">
          <div class="footer-classic-aside">
            <p class="rights"><span>&copy;&nbsp;</span><span class="copyright-year"></span>. All Rights Reserved. Design by <a href="#">SageSERV</a></p>
            <ul class="social-links">
              <li><a class="fa fa-linkedin" href="#"></a></li>
              <li><a class="fa fa fa-twitter" href="#"></a></li>
              <li><a class="fa fa-facebook" href="#"></a></li>
              <li><a class="fa fa-instagram" href="#"></a></li>
            </ul>
          </div>
        </div>
      </footer>

templates/snippets/navbar.html
{% load static %}
<div class="page">
  <header class="section page-header">
    <!--RD Navbar-->
    <div class="rd-navbar-wrap">
      <nav class="rd-navbar rd-navbar-classic" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-static" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-lg-stick-up-offset="46px" data-xl-stick-up-offset="46px" data-xxl-stick-up-offset="46px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
        <div class="rd-navbar-collapse-toggle rd-navbar-fixed-element-1" data-rd-navbar-toggle=".rd-navbar-collapse"><span></span></div>
        <div class="rd-navbar-aside-outer rd-navbar-collapse bg-gray-dark">
          <div class="rd-navbar-aside">
            <ul class="list-inline navbar-contact-list">
              <li>
                <div class="unit unit-spacing-xs align-items-center">
                  <div class="unit-left"><span class="icon text-middle fa-phone"></span></div>
                  <div class="unit-body"><a href="tel:#">+234-913-895-5830</a></div>
                </div>
              </li>
              <li>
                <div class="unit unit-spacing-xs align-items-center">
                  <div class="unit-left"><span class="icon text-middle fa-envelope"></span></div>
                  <div class="unit-body"><a href="mailto:#">inquiry@sageserv.tech</a></div>
                </div>
              </li>
              <li>
                <div class="unit unit-spacing-xs align-items-center">
                  <div class="unit-left"><span class="icon text-middle fa-map-marker"></span></div>
                  <div class="unit-body"><a href="#">Sage Security Services, No 22 Kano street, FCT-Abuja Nigeria.</a></div>
                </div>
              </li>
            </ul>
            <ul class="social-links">
              <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-linkedin" href="#"></a></li>
              <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-twitter" href="#"></a></li>
              <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-facebook" href="#"></a></li>
              <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-instagram" href="#"></a></li>
            </ul>
          </div>
        </div>
        <div class="rd-navbar-main-outer">
          <div class="rd-navbar-main">
            <!--RD Navbar Panel-->
            <div class="rd-navbar-panel">
              <!--RD Navbar Toggle-->
              <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
              <!--RD Navbar Brand-->
              <div class="rd-navbar-brand">
                <!--Brand--><a class="brand" href="{% url 'core:home' %}"><img class="brand-logo-dark" src="{% static 'images/logo-default-200x34.png' %}" alt="" /></a>
              </div>
            </div>
            <div class="rd-navbar-main-element">
              <div class="rd-navbar-nav-wrap">
                <ul class="rd-navbar-nav">
                  {% url 'core:home' as url %}
                  <li class="rd-nav-item {% if request.path == url %}active{% endif %}"><a class="rd-nav-link" href="{% url 'core:home' %}">Home</a></li>
                  {% url 'core:about' as url %}
                  <li class="rd-nav-item {% if request.path == url %}active{% endif %}"><a class="rd-nav-link" href="{% url 'core:about' %}">About</a></li>
                  {% url 'core:service' as url %}
                  <li class="rd-nav-item {% if request.path == url %}active{% endif %}"><a class="rd-nav-link" href="{% url 'core:service' %}">Services</a></li>
                  {% url 'core:recources' as url %}
                  <li class="rd-nav-item {% if request.path == url %}active{% endif %}"><a class="rd-nav-link" href="{% url 'core:recources' %}">Resources</a></li>
                  {% url 'core:finder' as url %}
                  <li class="rd-nav-item {% if request.path == url %}active{% endif %}"><a class="rd-nav-link" href="{% url 'core:finder' %}">Finder</a></li>
                  {% url 'core:contact' as url %}
                  <li class="rd-nav-item {% if request.path == url %}active{% endif %}"><a class="rd-nav-link" href="{% url 'core:contact' %}">Contact</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </header>